mutag_calibration:
  taggers:
    - globalParT_XbbVsQCDTop
  pt_binning:
    2022_preEE:
      - [250, 'Inf']
      - [250, 300]
      - [300, 350]
      - [350, 'Inf']
    2022_postEE:
      - [250, 'Inf']
      - [250, 300]
      - [300, 350]
      - [350, 'Inf']
    2023_preBPix:
      - [250, 'Inf']
      - [250, 300]
      - [300, 350]
      - [350, 'Inf']
    2023_postBPix:
      - [250, 'Inf']
      - [250, 300]
      - [300, 350]
      - [350, 'Inf']
  msd_binning:
    2022_preEE:
      - [40, 'Inf']
      - [80, 170]
    2022_postEE:
      - [40, 'Inf']
      - [80, 170]
    2023_preBPix:
      - [40, 'Inf']
      - [80, 170]
    2023_postBPix:
      - [40, 'Inf']
      - [80, 170]
  wp:
    2022_preEE:
      globalParT_XbbVsQCDTop:
        HHbbtt: 
         - 0.70
         - 0.75
         - 0.80
    2022_postEE:
      globalParT_XbbVsQCDTop:
        HHbbtt: 
         - 0.70
         - 0.75
         - 0.80
    2023_preBPix:
      globalParT_XbbVsQCDTop:
        HHbbtt: 
         - 0.70
         - 0.75
         - 0.80
    2023_postBPix:
      globalParT_XbbVsQCDTop:
        HHbbtt: 
         - 0.70
         - 0.75
         - 0.80
